### ISSUE TITLE
为什么1.0.3版本把服务启动事件的监听注释掉了

### ISSUE THREAD

**Issue by liuqiyang7** [lunasaw/zlm-spring-boot-starter#3]
为什么1.0.3版本把服务启动事件的监听注释掉了
<img width="880" alt="image" src="https://github.com/lunasaw/zlm-spring-boot-starter/assets/63906369/266ada2d-4c3a-4d11-bdf0-487ad61306e7">

**Comment by lunasaw** [comment]
> 为什么1.0.3版本把服务启动事件的监听注释掉了 <img alt="image" width="880" src="https://private-user-images.githubusercontent.com/63906369/329106403-266ada2d-4c3a-4d11-bdf0-487ad61306e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjYzNjgsIm5iZiI6MTcxODAyNjA2OCwicGF0aCI6Ii82MzkwNjM2OS8zMjkxMDY0MDMtMjY2YWRhMmQtNGMzYS00ZDExLWJkZjAtNDg3YWQ2MTMwNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEzMjc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmQ3OTg2ZmQ0NzU4MDZhNmJkMDJjNTFkMmFhZDRjOGJiYTA4YTMxYWRiZDcxNDRkYmYzMjRlYjVjMTI5ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EZ17cSVemHPK6Huw1L18QtVsvZorr-sZEQKy-KkHwk">

这个可能是写nodeconfig的时候没注意，你可以提个PR修复下

**Comment by lunasaw** [comment]
#4
